title: Oumi's Blog
description: >
  Thoughtful reflections on software development, written by a developer for developers.
baseurl: ""
url: "https://oumaimazerouali.github.io"
logo: "/assets/favicon/logo.svg"

author:
  name: "Oumaima Zerouali"
  email: oumaima.zerouali@gmail.com

social:
  name: Oumaima Zerouali
  links:
    - https://github.com/OumaimaZerouali
    - https://www.linkedin.com/in/oumaima-zerouali-16b189223/
    - https://www.instagram.com/_oumietje_/
    - https://jcast.dev

languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["assets", "js", "css", "img"]

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: en
      permalink: /:year/:month/:day/:title/
  - scope:
      path: "_posts/nl"
      type: "posts"
    values:
      lang: nl
      permalink: /nl/:year/:month/:day/:title/

linkedin_username: oumaima-zerouali-16b189223
github_username: OumaimaZerouali
instagram_username: _oumietje_

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
